version: "3.9"

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

services:
  redis:
    image: "redis:latest"
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  postgres:
    image: "postgres:latest"
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_NAME:-postgres}

  # sign up and connect to docker at local ip 192.168.x.x
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
